from django.http import JsonResponse

def index(request):
    if request.method == 'GET':
        data = None # do database response

        return JsonResponse({
            'status': 200,
            'data': {
                '_id': '[autogenerated id]',
                'name': 'John Doe',
                'image': '[some binary]',
                'longitude': '38.8951',
                'latitude': '-77.0364',
                'battery-level': 23,
            },
        })
    
    return JsonResponse({
        'status': 400,
    })
